<?php

/**
 * @file
 * This is the .module file for the Configuration Overview module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function config_overview_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.config_overview':
      return t('This module provides an overview of configurations status.');
  }
}

/**
 * Implements hook_theme().
 */
function config_overview_theme(array $existing, $type, $theme, $path) {
  return [
    'config_overview' => [
      'variables' => [
        'img_no' => NULL,
        'img_yes' => NULL,
        'display_protected_column_description' => NULL,
      ],
    ],
  ];
}
